// GIVEN a list of integers, remove any nodes that have values that have previously occurred in the list and return reference to the head of the list.
//Example:
// 3->4->3->6

// 3->4->6

// functional description: complete the function contains in the editor below,
//  condense has the following parammeters
//head of the s singly-linked list
// note: I linked list note node has two attributes: data, integer, and next reference to the next item in the list all the language equivalent of none at the tail.